mod function;
pub use function::*;
mod block;
pub use block::*;
mod instruction;
pub use instruction::*;
mod operand;
pub use operand::*;
mod constant;
pub use constant::*;
mod metadata;
pub use metadata::*;
mod global;
pub use global::*;
mod traits;
pub use traits::*;
