[package]
name = "llir"
version = "0.1.2"
authors = ["Ziyang Li <liby99@seas.upenn.edu>"]
license = "MIT"
description = "LLVM IR Binding"
repository = "https://github.com/liby99/llir"
keywords = ["llvm", "ir"]
edition = "2018"

[dependencies]
llvm-sys = "100"
libc = "0.2"