mod types;
pub use types::*;
mod void;
pub use void::*;
mod int;
pub use int::*;
mod float;
pub use float::*;
mod pointer;
pub use pointer::*;
mod array;
pub use array::*;
mod vector;
pub use vector::*;
mod struc;
pub use struc::*;
mod function;
pub use function::*;
mod traits;
pub use traits::*;
mod generic;
pub use generic::*;
