#[macro_use]
mod macros;
pub use macros::*;

mod opcode;

mod traits;
mod alloca;
mod binary;
mod br;
mod call;
mod call_br;
mod extract_value;
mod insert_value;
mod icmp;
mod indir_br;
mod fcmp;
mod gep;
mod instr;
mod load;
mod phi;
mod ret;
mod select;
mod store;
mod switch;
mod unary;
mod unreachable;

pub use opcode::*;
pub use traits::*;
pub use alloca::*;
pub use binary::*;
pub use br::*;
pub use call::*;
pub use call_br::*;
pub use extract_value::*;
pub use insert_value::*;
pub use icmp::*;
pub use indir_br::*;
pub use fcmp::*;
pub use gep::*;
pub use instr::*;
pub use load::*;
pub use phi::*;
pub use ret::*;
pub use select::*;
pub use store::*;
pub use switch::*;
pub use unary::*;
pub use unreachable::*;