mod alloca;
pub use alloca::*;
mod binary;
pub use binary::*;
mod br;
pub use br::*;
mod call;
pub use call::*;
mod call_br;
pub use call_br::*;
mod icmp;
pub use icmp::*;
mod indir_br;
pub use indir_br::*;
mod fcmp;
pub use fcmp::*;
mod gep;
pub use gep::*;
mod instr;
pub use instr::*;
mod load;
pub use load::*;
mod phi;
pub use phi::*;
mod ret;
pub use ret::*;
mod select;
pub use select::*;
mod store;
pub use store::*;
mod switch;
pub use switch::*;
mod unary;
pub use unary::*;
mod unreachable;
pub use unreachable::*;
mod traits;
pub use traits::*;
